fit:
    model:
      class_path: LResnet
      init_args:
        name: adv_train_deepfool
        num_target_classes: 10
        loss_module: 
          class_path: torch.nn.CrossEntropyLoss
        adv_train_method: 
          class_path: DeepfoolAttack
          init_args:
            max_iters: 50
            overshoot: 0.02
        pair_training: False
    data:
      class_path: CIFAR10DataModule
      init_args:
        data_dir: ./data
        batch_size: 128
    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.00001
        weight_decay: 0.1
    trainer:
      default_root_dir: models/cifar_checkpoints/adv_train_deepfool
      max_epochs: 100
      devices: 1
      logger: 
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs
          name: adv_train_deepfool
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args: 
            dirpath: models/cifar_checkpoints/adv_train_deepfool
            monitor: val_loss
            save_top_k: 1
            mode: min
            save_weights_only: False
            every_n_epochs: 1
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: val_loss
            patience: 3
            verbose: True
            mode: min

test:
    model:
      class_path: LResnet
      init_args:
        name: adv_train_deepfool
        num_target_classes: 10
        loss_module: 
          class_path: torch.nn.CrossEntropyLoss
          init_args:
            reduction: mean
        pair_training: False
        adv_test_method:
          class_path: idAttack
    data:
      class_path: CIFAR10DataModule
      init_args:
        data_dir: ./data
        batch_size: 128
    trainer:
      default_root_dir: models/cifar_checkpoints/adv_train_deepfool
      max_epochs: 100
      devices: 1
      logger: 
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs
          name: adv_train_deepfool
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args: 
            dirpath: models/cifar_checkpoints/adv_train_deepfool
            monitor: val_loss
            save_top_k: 1
            mode: min
            save_weights_only: False
            every_n_epochs: 1
    ckpt_path: /home/qz277/project/AMPs_refactored/pair_training/models/cifar_checkpoints/baseline/epoch=10-step=3443.ckpt