fit:
    model:
      class_path: LResnet
      init_args:
        name: baseline
        num_target_classes: 10
        loss_module: 
          class_path: torch.nn.CrossEntropyLoss
        pair_training: False
    data:
      class_path: CIFAR10DataModule
      init_args:
        data_dir: ./data
        batch_size: 128
    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 1e-5
        weight_decay: 0.1
    trainer:
      default_root_dir: models/cifar_checkpoints/baseline
      max_epochs: 100
      devices: 1
      logger: 
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs
          name: baseline
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args: 
            dirpath: models/cifar_checkpoints/baseline
            filename: baseline-best
            monitor: val_loss
            save_top_k: 1
            mode: min
            save_weights_only: False
            every_n_epochs: 1
        - class_path: lightning.pytorch.callbacks.EarlyStopping
          init_args:
            monitor: val_loss
            patience: 3
            verbose: True
            mode: min

test:
    model:
      class_path: LResnet
      init_args:
        name: baseline
        num_target_classes: 10
        loss_module: 
          class_path: torch.nn.CrossEntropyLoss
        pair_training: False
        adv_test_method:
          class_path: FGSMAttack
          init_args:
            loss_module: 
              class_path: torch.nn.CrossEntropyLoss
            eps: 0.031
            attack_type: untargeted
    data:
      class_path: CIFAR10DataModule
      init_args:
        data_dir: ./data
        batch_size: 128
    trainer:
      default_root_dir: models/cifar_checkpoints/baseline
      max_epochs: 100
      devices: 1
      logger: 
        class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: lightning_logs
          name: baseline
      callbacks:
        - class_path: lightning.pytorch.callbacks.ModelCheckpoint
          init_args: 
            dirpath: models/cifar_checkpoints/baseline
            monitor: val_loss
            save_top_k: 1
            mode: min
            save_weights_only: False
            every_n_epochs: 1
    ckpt_path: /home/qz277/project/AMPs_refactored/pair_training/models/cifar_checkpoints/baseline/baseline-best.ckpt